# Use root/example as user/password credentials
version: '3.8'

services:
  db:
    container_name: bas-nest-graphql-prisma-db
    image: mariadb
    restart: always
    ports:
      - 8890:3306
    environment:
      - MYSQL_ROOT_PASSWORD=dev
    volumes:
      - bas-nest-graphql-prisma-db:/var/lib/mysql

  adminer:
    container_name: bas-nest-graphql-prisma-adminer
    image: adminer
    restart: always
    ports:
      - 8891:8080
    depends_on:
      - db

volumes:
  bas-nest-graphql-prisma-db: {}
